/c video_games;


INSERT INTO vidya (editing_rights, name, type, price, language, Store_Link,   publisher, developer, platform, thumbnail, screenshot1, screenshot2, screenshot3, video, description) VALUES
(false, 'Advance Wars: Dual Strike','Turn Based Strategy', 30, 'English', 'https://www.gamestop.com/products/advance-wars-dual-strike---nintendo-ds/919020.html', 
'Nintendo', 'Intelligent Systems', 'Nintendo DS','https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/11a10a01-ac23-4fea-ad5a-b51f53084159/dcood0h-565d5327-42ee-48e2-a913-324bbcfccb7d.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzExYTEwYTAxLWFjMjMtNGZlYS1hZDVhLWI1MWY1MzA4NDE1OVwvZGNvb2QwaC01NjVkNTMyNy00MmVlLTQ4ZTItYTkxMy0zMjRiYmNmY2NiN2QucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.jHNOMlOKgebrcvcODo-jOCaa-uW8OWCBeWaQD9OsgBM',
'https://www.mobygames.com/images/shots/l/404441-advance-wars-dual-strike-nintendo-ds-screenshot-the-battle.png', 'https://koopanique.neocities.org/video_games/video_games_pictures/advance_wars2.JPG', 'https://i.ytimg.com/vi/NpGoGBOBfMg/maxresdefault.jpg', 'https://www.youtube.com/watch?v=-0YI41OfAlM',
'A simple, yet surprisingly in-depth turn-based tactics game developed for the DS as the sequel to Advance Wars 2, Black Hole Rising. Additional features include several new units and commanders, a dual commander and battlefield system and the addition of the Dual Strike super power mechanic.'),

(false, 'Escape From Tarkov','Realistic Multiplayer RPG Survival Shooter', 45, 'English/Russian',  'https://www.escapefromtarkov.com/preorder-page', 'Battlestate Games', 'Battlestate Games', 'PC', 
'https://www.pngall.com/wp-content/uploads/5/Escape-From-Tarkov-PNG-File.png', 'https://www.escapefromtarkov.com/uploads/filemanager/files/eft_alpha_woods12.jpg', 'https://install-game.com/wp-content/uploads/2019/04/Escape-From-Tarkov-Screenshots-2.jpg',
'https://www.guru3d.com/index.php?ct=news&action=file&id=19425', 'https://www.youtube.com/watch?v=ilN-Juv6sVw', 'A realistic and brutal survival shooter set in the fictional Russian city of Tarkov where lawlessness reigns. Scavenge, run, and kill to survive another day. Welcome to Tarkov where survival is your resposnbility.'),

(false, 'Ragnarok Online', '2.5D Fantasy MMORPG', 0, 'English/Korean', 'https://store.steampowered.com/app/215100/Ragnarok_Online/', 'Gravity Interactive', 'Gravity Interactive','PC',
'https://scontent-lga3-1.xx.fbcdn.net/v/t1.18169-9/11119432_1433618886941703_6407382762335033907_n.png?_nc_cat=102&ccb=1-7&_nc_sid=85a577&_nc_ohc=EY_j9ZjKv2MAX9g9_fW&_nc_ht=scontent-lga3-1.xx&oh=00_AT9votuLg6a-2-Wmf0r7ew2hkcbidfwaavfdT3iIJ9EInQ&oe=633D61AA',
'https://i.ytimg.com/vi/pi4B8v_h7nE/maxresdefault.jpg', 'https://www.dlh.net/public/data/cache/1280x0/8417252130e0e8e96f2d840e99845166e6ffa0ed.PNG', 'http://i.imgur.com/CNCMfm0.jpg', 'https://www.youtube.com/watch?v=4l2Gi77oM9M', 'An old-school Korean MMO released in 2003 with art and music quality second to none and a die hard loyal fanbase. A game that I regard fondly, having played it from my childhood to this day.' ),

(false, 'The Elder Scrolls IV: Oblivion','Fantasy RPG', 15, 'English', 'https://store.steampowered.com/app/22330/The_Elder_Scrolls_IV_Oblivion_Game_of_the_Year_Edition/', 'Bethesda Softworks', 'Bethesda Game Studios', 'PS3/XBOX 360/PC',
 'https://icons.iconarchive.com/icons/skullboarder/games/256/Oblivion-icon.png', 'https://ip.trueachievements.com/remote/download.xbox.com/content/images/66acd000-77fe-1000-9115-d802425307d1/1033/screenlg5.jpg?width=900', 'https://www.imperial-library.info/sites/default/files/imagecache/node-gallery-display/gallery_files/obps315B.jpg',
 'https://images.purexbox.com/screenshots/113027/large.jpg', 'https://www.youtube.com/watch?v=IPZZf0S2paY', 'The game that bethesda refuses to remaster despite beating the Skyrim remaster cash cow to death. If you can get past the ugly character models and archaic combat system, your in for a good time wandering throughout Cyrodil. '),

(false, 'Command & Conquer 2: Red Alert','Real Time Strategy', 5, 'English', 'https://www.origin.com/usa/en-us/store/command-and-conquer/command-and-conquer-the-ultimate-collection/interstitial', 'EA Games', 'EA Pacific/Westwood Studios', 'PC', 'https://www.mobygames.com/images/promo/original/1517376907-664458095.jpg', 
'https://images.gamewatcherstatic.com/screenshot/image/9/03/219949/00001214.jpg','https://www.mobygames.com/images/promo/original/1517376818-1502481805.jpg', 'https://media.moddb.com/cache/images/mods/1/1/703/thumb_620x2000/16368.jpg', 'https://www.youtube.com/watch?v=j5OShtDc-9g','Set in a fictional timeline after the events of Red Alert 1, where the Cold War went hot but no nukes were used. 
The Soviets having lost the last war against the US seek to invade America and topple the Allies with the help of their psychic esper Yuri. Play as either the Soviet or Allied Commander and guide your faction to victory. Welcome back Commander.' ),

(false, 'War Thunder', 'Realistic Vehicle Combat Simulation', 0, 'English', 'https://store.steampowered.com/app/236390/War_Thunder/', 'Gaijin Distribution KFT', 'Gaijin Entertainment', 'PS4/XBOX ONE/PC', 'https://cdn1.idcgames.com/storage/image/1138/thumb_slider/default.jpg', 'https://www.xboxone-hq.com/images/games/screenshots/2060-war-thunder-screenshot-2-1529780383.jpg',
'https://static.warthunder.com/upload/image/1000x700/july_screen7.jpg', 'https://i.redd.it/0qtfk3vwa1x81.png', 'https://www.youtube.com/watch?v=C2QtP56KpfM', 'A free 2 play realistic multiplayer vehicle combat simulator, engage against other players in technically and historically accurate vehicles, aircraft, and ships. From lightly armored cars, biplanes, and torpedo boats of pre-World-War II to state of the art main battle tanks, helicopters, jetfighters, and missile cruisers of modern military arsenals, 
every military history buffs favorite game.'),

(false, 'Megaman X5', '2D Platformer', 20, 'English/Japanese', 'https://store.steampowered.com/app/743900/Mega_Man_X_Legacy_Collection_2/', 'Capcom', 'Capcom', 'PS1/PC', 'https://e7.pngegg.com/pngimages/264/886/png-clipart-mega-man-x5-mega-man-x4-mega-man-xtreme-2-mega-man-x3-atari-2600-logo-text-logo-thumbnail.png',
 'https://www.mobygames.com/images/shots/l/192433-mega-man-x5-playstation-screenshot-zero-is-using-his-z-saber.jpg', 'https://i0.wp.com/gamecomplaintdepartment.com/wp-content/uploads/2018/08/292426-mega-man-x5-windows-screenshot-somebody-needs-your-help.jpg?w=640&ssl=1', 'https://www.denofgeek.com/wp-content/uploads/2018/06/mega_man.jpg?resize=768%2C432'
 ,'https://www.youtube.com/watch?v=asL1srThg7Y&t=1162s', 'Sequel to Megaman x4, play as either Zero or X, maverick hunters and partners in crime as you set out to stop Sigma from crashing a space colony onto Earth.'),

(false, 'Fallout New Vegas', 'RPG Shooter', 10, 'English', 'https://store.steampowered.com/app/22380/Fallout_New_Vegas/', 'Bethesda Softworks', 'Obsidian Entertainment', 'PS3/XBOX 360/PC', 'https://cdn.cloudflare.steamstatic.com/steam/apps/22380/header.jpg?t=1586905021', 'https://www.meme-arsenal.com/memes/34f1504ed24097ee70f211726213edeb.jpg',
'https://sfx.thelazy.net/media/medthumb/9_3.jpg', 'https://www.nma-fallout.com/data/photos/l/3/3457-1276637922-138a3f97d2582bab86538c8ddf1ab213.jpg', 'https://www.youtube.com/watch?v=IMaNCgyjVmg', 'Set in the post-nuclear world of Fallout, you awake as the Courier someone who was shot in the head and left for dead as the assailants stole whatever package you were tasked with delivering
to New Vegas. Having been patched up by a doctor in the town of Goodsprings, you set out on the lonesome and perilous road to New Vegas seeking answers and vengeance ignorant of how your actions would shape the Mojave Wasteland for years to come.'),

(false, 'Yakuza 0', 'JRPG', 20, 'Japanese', 'https://store.steampowered.com/app/638970/Yakuza_0/', 'SEGA', 'SEGA', 'PS4/PC', 'https://cdn.cloudflare.steamstatic.com/steam/apps/638970/header.jpg?t=1633021581', 'https://www.newgamenetwork.com/images/uploads/gallery/Yakuza0/yakuza0_09.jpg',
'https://external-preview.redd.it/qF_Ytt3JExm_14rYFjZYULiypRUAt_1RVn3PSJhj07w.jpg?auto=webp&s=ffc9fe7d4ffb051e68f3e3baf1392994b846b58e','https://cdn.akamai.steamstatic.com/steam/apps/638970/ss_bcda5d10659c03acb555330d6059681c3cdc72ee.1920x1080.jpg?t=1633021581', 'https://www.youtube.com/watch?v=jmAOt9K_u0o', 'A crime drama featuring dual protagonists Majima Goro and Kiryu Kazuma, set in Japan in the 1980s where crime, decadence, and high times were rampant riding the Japanese asset bubble of the 80s.
Our protagonists get caught up in an internal power struggle within the Tojo Clan as Kiryu is accused of murdering a man within an empty lot the Clan wanted to buy and Majima having been tasked with killing Makoto, a blind woman who holds the deeds to the empty lot where Kiryu supposedly murdered the man. Our protagonists are tested 
as they have to make a decision between their loyalty to their clans or loyalty to their values and those they vow to protect.'),

(false, 'Persona 4 Golden', 'JRPG', 20, 'Japanese/English', 'https://store.steampowered.com/app/1113000/Persona_4_Golden/', 'SEGA', 'ATLUS', 'PSVITA/PC', 'https://steamcdn-a.akamaihd.net/steam/apps/1113000/header.jpg', 'https://maroonersrock.com/wp-content/uploads/2020/06/Persona-4-Golden-Screenshots.jpg',
'https://www.giantbomb.com/a/uploads/original/0/3454/2769103-2013-07-10-152012.jpg', 'https://gamefabrique.com/storage/screenshots/pc/persona-4-golden-05.png', 'https://www.youtube.com/watch?v=GKMsyH6mueE', 'Set in the rural Japanese town of Inaba, you play as a high school transfer student who moved from the city to Inaba for a year as your parents work overseas.
As you get accustomed to life in Inaba you hear rumors where if you stare at your tv during midnight your soulmate is revealed to you. On a foggy night you test the rumor only to find someone on the tv writhing in pain. Spooked, you decide to sleep and talk about it to your newly made friends the next day in class. As the fog clears in the morning a dead body is left its wake, tangled and dangling on an electrical post not far from your school.... '),

(false, 'Hotline Miami', 'Top Down Shooter', 10, 'English', 'https://store.steampowered.com/app/219150/Hotline_Miami/', 'Devolver Digital', 'Dennaton Games', 'PS4/XBOX ONE/PC', 'https://e7.pngegg.com/pngimages/907/358/png-clipart-hotline-miami-2-wrong-number-dennaton-games-video-game-superhot-others-miscellaneous-text-thumbnail.png', 'https://i.redd.it/wojf9vkvoqg31.jpg',
'https://cdn.vox-cdn.com/uploads/chorus_asset/file/2640284/Hotline-Miami---Gamescom-1.1344894842.jpg', 'https://cdn.thegamesdb.net/images/original/screenshots/18228-1.jpg', 'https://www.youtube.com/watch?v=mWKqq0VtyJY', 'A visceral, intense, and unforgiving top-down shooter set in an alternate 1989 Miami, Florida in which the player murders their way through the American branch of the Russian mafia on behalf of an unknown organization.
As your jobs become more and more dangerous, you start to uncover clues into whos been leaving the messages on your phone and their motives into goading people into attacking the Russian mafia.');
